///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace FirstTEST
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the FirstTESTRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("e78362eb-71a6-4fc1-bc96-bda597bbb43e")]
    public partial class FirstTESTRepository : RepoGenBaseFolder
    {
        static FirstTESTRepository instance = new FirstTESTRepository();
        FirstTESTRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        FirstTESTRepositoryFolders.NewTabAppFolder _newtab;

        /// <summary>
        /// Gets the singleton class instance representing the FirstTESTRepository element repository.
        /// </summary>
        [RepositoryFolder("e78362eb-71a6-4fc1-bc96-bda597bbb43e")]
        public static FirstTESTRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public FirstTESTRepository() 
            : base("FirstTESTRepository", "/", null, 0, false, "e78362eb-71a6-4fc1-bc96-bda597bbb43e", ".\\RepositoryImages\\FirstTESTRepositorye78362eb.rximgres")
        {
            _applicationundertest = new FirstTESTRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _newtab = new FirstTESTRepositoryFolders.NewTabAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("e78362eb-71a6-4fc1-bc96-bda597bbb43e")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("5af76ec1-bbfc-4a50-ae95-65bf81aeb717")]
        public virtual FirstTESTRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The NewTab folder.
        /// </summary>
        [RepositoryFolder("b0dc9945-9b64-4a81-95fa-7b9771047106")]
        public virtual FirstTESTRepositoryFolders.NewTabAppFolder NewTab
        {
            get { return _newtab; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class FirstTESTRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("5af76ec1-bbfc-4a50-ae95-65bf81aeb717")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, false, "5af76ec1-bbfc-4a50-ae95-65bf81aeb717", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5af76ec1-bbfc-4a50-ae95-65bf81aeb717")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5af76ec1-bbfc-4a50-ae95-65bf81aeb717")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The NewTabAppFolder folder.
        /// </summary>
        [RepositoryFolder("b0dc9945-9b64-4a81-95fa-7b9771047106")]
        public partial class NewTabAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new NewTab  folder.
            /// </summary>
            public NewTabAppFolder(RepoGenBaseFolder parentFolder) :
                    base("NewTab", "/dom[@domain='newtab']", parentFolder, 30000, null, false, "b0dc9945-9b64-4a81-95fa-7b9771047106", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b0dc9945-9b64-4a81-95fa-7b9771047106")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b0dc9945-9b64-4a81-95fa-7b9771047106")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
